-- MySQL Script generated by MySQL Workbench
-- Tue Sep 29 20:19:35 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`projeto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`projeto` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `nome_projeto` VARCHAR(30) NOT NULL,
  `registro_funcionario` INT NOT NULL,
  `horas_estimadas` FLOAT NOT NULL,
  PRIMARY KEY (`codigo`, `registro_funcionario`),
  INDEX `fk_projeto_funcionario_idx` (`registro_funcionario` ASC) VISIBLE,
  CONSTRAINT `fk_projeto_funcionario`
    FOREIGN KEY (`registro_funcionario`)
    REFERENCES `mydb`.`funcionario` (`registro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`funcionario` (
  `registro` INT NOT NULL AUTO_INCREMENT,
  `nome_funcionario` VARCHAR(50) NOT NULL,
  `horas_semanais` FLOAT NOT NULL,
  `codigo_projeto` INT,
  PRIMARY KEY (`registro`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

drop database mydb;
INSERT INTO funcionario values (1,'Jonas',40,0);
INSERT INTO projeto values (1,'ProjetoAICO',1,800);
UPDATE funcionario SET codigo_projeto = 1 WHERE registro = 1;
INSERT INTO funcionario values (2,'Ana',40,1);
INSERT INTO funcionario values (3,'Luiza',40,0);

select * from `projeto`;
select * from `funcionario`;

SELECT projeto.codigo, projeto.nome_projeto, funcionario.nome_funcionario, projeto.horas_estimadas
FROM projeto, funcionario
WHERE funcionario.registro = projeto.registro_funcionario;

SELECT funcionario.registro, funcionario.nome_funcionario, projeto.nome_projeto, funcionario.codigo_projeto, funcionario.horas_semanais
FROM funcionario, projeto
WHERE projeto.codigo = funcionario.codigo_projeto or funcionario.codigo_projeto = 0;

# Atualizar o funcionario responsavel durante a criação do projeto
UPDATE funcionario SET codigo_projeto = 1 WHERE registro = 1;
